(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},ca=ba(this),da=function(a,b){if(b)a:{var c=ca;a=a.split(".");for(var e=0;e<
a.length-1;e++){var f=a[e];if(!(f in c))break a;c=c[f]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&aa(c,a,{configurable:!0,writable:!0,value:b})}},ea="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},d;
if("function"==typeof Object.setPrototypeOf)d=Object.setPrototypeOf;else{var l;a:{var fa={a:!0},m={};try{m.__proto__=fa;l=m.a;break a}catch(a){}l=!1}d=l?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var n=d;
da("Array.from",function(a){return a?a:function(b,c,e){c=null!=c?c:function(k){return k};var f=[],h="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof h){b=h.call(b);for(var g=0;!(h=b.next()).done;)f.push(c.call(e,h.value,g++))}else for(h=b.length,g=0;g<h;g++)f.push(c.call(e,b[g],g));return f}});var p=this||self,q=function(a){return a};var ha=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,b,void 0)}:function(a,b){for(var c=a.length,e="string"===typeof a?a.split(""):a,f=0;f<c;f++)if(f in e&&b.call(void 0,e[f],f,a))return!0;return!1};var r,t=function(){if(void 0===r){var a=null,b=p.trustedTypes;if(b&&b.createPolicy){try{a=b.createPolicy("goog#html",{createHTML:q,createScript:q,createScriptURL:q})}catch(c){p.console&&p.console.error(c.message)}r=a}else r=a}return r};var w=function(a,b){this.g=b===u?a:""};w.prototype.toString=function(){return this.g+""};var u={};var x;a:{var y=p.navigator;if(y){var z=y.userAgent;if(z){x=z;break a}}x=""};var B=function(a,b,c){this.g=c===A?a:""};B.prototype.toString=function(){return this.g.toString()};var A={};var D=null,ia=/^[\w+/_-]+[=]{0,2}$/,ja=function(a){return a.querySelector?(a=a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&ia.test(a)?a:"":""};var ka={},E=null;var la="function"===typeof Uint8Array;var F=function(){},ma=[],na=function(a){var b=a.i+a.m;a.g[b]||(a.h=a.g[b]={})},G=function(a,b,c){b<a.i?a.g[b+a.m]=c:(na(a),a.h[b]=c);return a},H=function(a){if(a.j)for(var b in a.j){var c=a.j[b];if(Array.isArray(c))for(var e=0;e<c.length;e++)c[e]&&H(c[e]);else c&&H(c)}return a.g};
F.prototype.s=la?function(){var a=Uint8Array.prototype.toJSON;Uint8Array.prototype.toJSON=function(){var b;void 0===b&&(b=0);if(!E){E={};for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),e=["+/=","+/","-_=","-_.","-_"],f=0;5>f;f++){var h=c.concat(e[f].split(""));ka[f]=h;for(var g=0;g<h.length;g++){var k=h[g];void 0===E[k]&&(E[k]=g)}}}b=ka[b];c=[];for(e=0;e<this.length;e+=3){var C=this[e],v=(f=e+1<this.length)?this[e+1]:0;k=(h=e+2<this.length)?this[e+2]:0;g=C>>2;
C=(C&3)<<4|v>>4;v=(v&15)<<2|k>>6;k&=63;h||(k=64,f||(v=64));c.push(b[g],b[C],b[v]||"",b[k]||"")}return c.join("")};try{return JSON.stringify(this.g&&H(this),oa)}finally{Uint8Array.prototype.toJSON=a}}:function(){return JSON.stringify(this.g&&H(this),oa)};var oa=function(a,b){return"number"!==typeof b||!isNaN(b)&&Infinity!==b&&-Infinity!==b?b:String(b)};F.prototype.toString=function(){return H(this).toString()};var I=function(a){var b=a;a=pa;this.j=null;b||(b=[]);this.m=-1;this.g=b;a:{if(b=this.g.length){--b;var c=this.g[b];if(!(null===c||"object"!=typeof c||Array.isArray(c)||la&&c instanceof Uint8Array)){this.i=b- -1;this.h=c;break a}}this.i=Number.MAX_VALUE}if(a)for(b=0;b<a.length;b++)c=a[b],c<this.i?(c+=-1,this.g[c]=this.g[c]||ma):(na(this),this.h[c]=this.h[c]||ma)};I.prototype=ea(F.prototype);I.prototype.constructor=I;
if(n)n(I,F);else for(var J in F)if("prototype"!=J)if(Object.defineProperties){var qa=Object.getOwnPropertyDescriptor(F,J);qa&&Object.defineProperty(I,J,qa)}else I[J]=F[J];var pa=[6];var ta=function(a,b){if(!ra()){var c=Math.random();if(c<b)return c=sa(),a[Math.floor(c*a.length)]}return null},sa=function(){if(!p.crypto)return Math.random();try{var a=new Uint32Array(1);p.crypto.getRandomValues(a);return a[0]/65536/65536}catch(b){return Math.random()}},ra=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){return ha(["Google Web Preview","Mediapartners-Google","Google-Read-Aloud","Google-Adwords"],ua)||1E-4>Math.random()}),ua=function(a){return-1!=x.indexOf(a)};var va=["platform","platformVersion","architecture","model","uaFullVersion"],wa=function(){return p.navigator&&p.navigator.userAgentData&&"function"===typeof p.navigator.userAgentData.getHighEntropyValues?p.navigator.userAgentData.getHighEntropyValues(va).then(function(a){var b=new I;b=G(b,1,a.platform);b=G(b,2,a.platformVersion);b=G(b,3,a.architecture);b=G(b,4,a.model);return G(b,5,a.uaFullVersion)}):null};var xa=function(a,b){b=void 0===b?!0:b;try{for(var c=null;c!=a;c=a,a=a.parent)switch(a.location.protocol){case "https:":return!0;case "file:":return b;case "http:":return!1}}catch(e){}return!0}(p,!1)?"https:":"http:";var ya={F:1,v:4,A:5,u:7,B:9,C:10,D:11},K={o:"40004006",l:"40004007"};function za(){return{1:.5,4:.02,5:.001,7:.5,9:.05,10:.2,11:.01}}function Aa(){var a=Ba,b=typeof a;if(("object"!=b||null==a)&&"function"!=b)return!1;for(var c in ya)if(b=a[ya[c]],"number"!==typeof b||0>b||1<b)return!1;return!0};function Ca(){var a=p.dcmads;if(null!=a.eids)return a.eids;var b=p.navigator;return b.connection&&b.connection.saveData?(a=ta([K.o,K.l],a.expts[4]))?"4|"+a:"":""}function Da(){if(!p.dcmads.uach){var a=wa();a&&a.then(function(b){p.dcmads.uach=b.s()})}};try{p.dcmads=p.dcmads||{};p.dcmads.startTime=(new Date).getTime();var Ea=p.dcmads,L=p.dcmads.version,M={loader:205};if(L)if(M.experiment=L.experiment,71==L.number||"p"==L.number)M.number=71;else if(71==L.number||"c"==L.number)M.number=71;if(!M.number){var Fa=ta([71,71],0);M.experiment=!!Fa;M.number=Fa||71}Ea.version=M;var Ga=p.dcmads,Ha,Ba=p.dcmads.expts,N;N=void 0===N?za:N;Ha=Aa()?Ba:N();Ga.expts=Ha;p.dcmads.eids=Ca();Da();var Ia="4|"+K.l,Ja=p.dcmads.version,Ka=Ja.number,La="";Ja.experiment&&71==
Ka&&(La="?rxp=71x71");var Ma="impl_v"+Ka+".js"+La,Na=p.document,Oa=Na.currentScript||Array.from(Na.getElementsByTagName("script")).pop(),O=(0==(Oa&&Oa.src||"").indexOf("http:")?"http:":"https:")+"//www.googletagservices.com/dcm/"+Ma;if(p.dcmads.eids===Ia){var Pa=p.document,Qa=t(),Ra=Qa?Qa.createScriptURL(O):O,P=Pa.createElement("script"),Q=new w(Ra,u);P.src=Q instanceof w&&Q.constructor===w?Q.g:"type_error:TrustedResourceUrl";var R;var S=P.ownerDocument&&P.ownerDocument.defaultView;S&&S!=p?R=ja(S.document):
(null===D&&(D=ja(p.document)),R=D);var Sa=R;Sa&&P.setAttribute("nonce",Sa);var T=Pa.getElementsByTagName("script")[0];T&&T.parentNode&&T.parentNode.insertBefore(P,T)}else{var Ta=p.document,U,Ua='<script src="'+O+'">\x3c/script>',Va=t(),Wa=Va?Va.createHTML(Ua):Ua;U=new B(Wa,null,A);Ta.write(U instanceof B&&U.constructor===B?U.g:"type_error:SafeHtml")}}catch(a){if(.01>Math.random()){var V="";try{var W,X=a.toString();a.name&&-1==X.indexOf(a.name)&&(X+=": "+a.name);a.message&&-1==X.indexOf(a.message)&&
(X+=": "+a.message);if(a.stack){var Y=a.stack,Z=X;try{-1==Y.indexOf(Z)&&(Y=Z+"\n"+Y);for(var Xa;Y!=Xa;)Xa=Y,Y=Y.replace(/((https?:\/..*\/)[^\/:]*:\d+(?:.|\n)*)\2/,"$1");X=Y.replace(/\n */g,"\n")}catch(b){X=Z}}W=X;W=W.substring(0,1024);V=encodeURIComponent(W)}catch(b){V="extr"}var Ya=p.dcmads.eids,Za=document.createElement("img");Za.src=xa+"//pagead2.googlesyndication.com/pagead/gen_204?id=dcmads-err&ver=205&context=554"+((Ya?"&eids="+Ya:"")+"&msg="+V);(p.google_image_requests=p.google_image_requests||
[]).push(Za)}};}).call(this);
